### ISSUE TITLE
How to configure swagger for localhost?

### ISSUE THREAD

**Issue by donny08** [tonguetech/express-typescript-seed#2]
I run node appliaction and browse the url: **http://localhost:8080/api-docs/swagger/assets/**. Currently the swagger url pointing to https://petstore.swagger.io/v2.

**Comment by dicksonchow** [comment]
Sorry that this has been procrastinated for quite a while. My latest pull request https://github.com/tonguetech/express-typescript-seed/pull/4 should fix the problem.
